default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= Rails.application.credentials.dig(:rails_max_threads) %>

development:
  <<: *default
  database: superonce_development

test:
  <<: *default
  database: superonce_test

production:
  primary: &primary_production
    <<: *default
    url: <%= Rails.application.credentials.dig(:database, :url) %>
    pool: <%= Rails.application.credentials.dig(:database, :pool) %>
    database: superonce_production
  cache:
    <<: *primary_production
    database: superonce_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: superonce_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: superonce_production_cable
    migrations_paths: db/cable_migrate